#!/bin/bash
#
# sustain - If the internet connection is currently down, then fix it and continue to scan for any lapses in connectivity. If the internet is already up, then exit.

sustain5 &
soft
sleep 15
f
sleep 15
pi

